### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by Divyesh-Kamalanaban** [samyukt-g/DarkModeToggle#1]
Try using Google Fonts for a uniform font family across all platforms. You've used Segoe UI which is a windows exclusive. Try using the system font family in css, which gives it a uniform UX.

**Comment by samyukt-g** [comment]
Thank you!!! Will do that, its actually a very helpful issue!

**Comment by Divyesh-Kamalanaban** [comment]
Since the repository owner has agreed to fix it, I have closed this issue.
